name: shoredetect
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - imageio
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - opencv
  - pandas
  - python=3.7
  - pytorch
  - scikit-learn
  - scipy
  - torchvision
  - pip:
    - imgaug
    - pillow
    - scikit-image
